### ISSUE TITLE
pass it as an option.. i don't know where to go from here

### ISSUE THREAD

**Issue by uinguzero** [reugn/gemini-cli#15]
I installed your app i added my api key to the environment variable GIMINI_API_KEY, but it still says
```
then pass it as an option:
genai.NewClient(ctx, option.WithAPIKey(os.Getenv("GEMINI_API_KEY")))
```

Since i am new to go, what do i need to ? 
Where do i need to pass this option?

**Comment by reugn** [comment]
@uinguzero, ensure that the variable name `GEMINI_API_KEY` is spelled correctly when assigning the key.
