### ISSUE TITLE
Toggling between single line and multi-line  

### ISSUE THREAD

**Issue by ImSreyas** [reugn/gemini-cli#19]
### How to send the request if you are in multi-line?
pressing enter only creates new line
i have tried some key combination with enter, and no luck

### How to toggle back to single line?
if you enter to multi-line using `!m`, how to go back to single line
giving `!m` in the multi line is not working

**Comment by reugn** [comment]
Use `$` to terminate a request when in the multi-line mode. A custom terminator string can be specified using the `-t` or `--term` flags, see [CLI help](https://github.com/reugn/gemini-cli?tab=readme-ov-file#cli-help).

**Comment by ImSreyas** [comment]
> Use `$` to terminate a request when in the multi-line mode. A custom terminator string can be specified using the `-t` or `--term` flags, see [CLI help](https://github.com/reugn/gemini-cli?tab=readme-ov-file#cli-help).

**Thank you...** ❤️
It would've been better if it is available in the  [system commands](https://github.com/reugn/gemini-cli?tab=readme-ov-file#system-commands) section on readme.
then i would've noticed it earlier...

**Comment by ImSreyas** [comment]
Is it anyway possible to have the below given behaviour?

shift+enter to create new line,
enter to submit the query.

**Comment by reugn** [comment]
Key combinations will be problematic when pasting a multi-line query.
