### ISSUE TITLE
Reuse older conversations with the AI

### ISSUE THREAD

**Issue by gabriel7419** [reugn/gemini-cli#21]
So I don't know if it is already a feature but I didn't manage to find a way to resume older conversations I had previously with the AI. 
For long-term courses, for example, it is crucial to have the AI to remember my progress.

**Comment by reugn** [comment]
Yes, the application currently does not retain chat history after closing.

**Comment by reugn** [comment]
@gabriel7419, [v0.4.0](https://github.com/reugn/gemini-cli/releases/tag/v0.4.0) now supports storing and loading chat history.

**Comment by gabriel7419** [comment]
Thank you so much, it wil lhelp alot.
