### ISSUE TITLE
Updating to include gemini 2.0 flash 

### ISSUE THREAD

**Issue by Bearmancer** [reugn/gemini-cli#35]
With the recent release of 2.0, are there plans to update the script to include the newest models?

**Comment by reugn** [comment]
The application calls the API to list all available models. The result is cached, so you may need to restart. Use the system command `m` to select a model and check if `models/gemini-2.0-flash-exp` is in the list.
This feature is not available in `v0.3.1` and will be released soon. Build from source to get the latest updates.
